{% set name = "types-retry" %}
{% set version = "0.9.9.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/types-retry-{{ version }}.tar.gz
  sha256: e4731dc684b56b875d9746459ad665d3bc281a56b530acdf1c97730167799941

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  commands:
    - test -f $SP_DIR/retry-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for retry
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
