{% set version = "0.9.9.20250322" %}

package:
  name: types-retry
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/t/types-retry/types_retry-{{ version }}.tar.gz
  sha256: 2eaa6f4b832c187121056988bbe6d2d0b6f4eb03631fdc9752e2ac2802f7b726

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check
    - test -f $SP_DIR/retry-stubs/__init__.pyi

about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for retry
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
